# Generated by Django 5.1.3 on 2024-11-26 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0003_lecture_practice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
                ('year', models.IntegerField(verbose_name='Год обучения')),
                ('group_number', models.IntegerField(verbose_name='Номер группы')),
                ('courses', models.ManyToManyField(related_name='groups', to='bd.course')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='bd.group'),
        ),
    ]
